// pages/_app.js or any other component where you want to apply this

import { Inter } from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // style={{ userSelect: 'none' }}
  return (
    <html lang="en">
      <body className={inter.className} >
        
        {children}
      </body>
    </html>
  );
}
